artifactory:
  image: docker.bintray.io/jfrog/artifactory-oss
  ports:
    - 8080:8081
  volumes:
    - /etc/opt/jfrog/artifactory
    - /var/opt/jfrog/artifactory/data
    - /var/opt/jfrog/artifactory/logs
